name: 'ais_data_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ais_data_profile'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  ais_data_project:
    # Config defaults for all models in this project
    +materialized: view
    
    # Staging models configuration
    staging:
      +materialized: view
      +schema: staging
    
    # Curated models configuration
    curated:
      +materialized: table
      +schema: curated
    
    # Mart models configuration for dashboards
    marts:
      +materialized: table
      +schema: marts
