version: 2

models:
  - name: daily_navigational_status
    description: >
      Daily aggregation of AIS data showing the distribution of navigational statuses by day.
      This model is optimized for visualization in a pie chart showing daily distribution.
    columns:
      - name: date
        description: The date of the records
        tests:
          - not_null
      
      - name: navigational_status
        description: The navigational status of the vessel
        tests:
          - not_null
      
      - name: record_count
        description: Count of records for a given navigational status on a specific date
        tests:
          - not_null
      
      - name: total_daily_records
        description: Total count of records for the date
        tests:
          - not_null
      
      - name: percentage
        description: Percentage of records with this navigational status for the date (0-100)
  
  - name: monthly_navigational_status
    description: >
      Monthly aggregation of AIS data showing the distribution of navigational statuses by month.
      This model is optimized for visualization in a time series chart showing monthly trends.
    columns:
      - name: month_start_date
        description: The first day of the month, used for partitioning and time-based filtering
        tests:
          - not_null
      
      - name: year
        description: The year component extracted from the timestamp
        tests:
          - not_null
      
      - name: month
        description: The month component (1-12) extracted from the timestamp
        tests:
          - not_null
      
      - name: navigational_status
        description: The navigational status of the vessel
        tests:
          - not_null
      
      - name: record_count
        description: Count of records for a given navigational status in a specific month
        tests:
          - not_null
      
      - name: total_monthly_records
        description: Total count of records for the month
        tests:
          - not_null
      
      - name: percentage
        description: Percentage of records with this navigational status for the month (0-100)
