version: 2

models:
  - name: daily_nav_status
    description: >
      Aggregates AIS navigational status data by day.
      This model is used for powering the navigational status pie chart dashboard.
    columns:
      - name: event_date
        description: Date of the AIS data records
        tests:
          - not_null
      
      - name: navigational_status
        description: The navigational status reported by the vessel
        tests:
          - not_null
      
      - name: vessel_count
        description: Count of distinct vessels (by MMSI) for each navigational status per day
        tests:
          - not_null
      
      - name: record_count
        description: Total count of AIS records for each navigational status per day
        tests:
          - not_null
      
      - name: movement_status
        description: Categorized movement status (Anchored, Moored, Moving, Other)
      
      - name: generated_at
        description: Timestamp when this data was generated

  - name: monthly_nav_status
    description: >
      Aggregates AIS navigational status data by month.
      This model is used for powering the monthly navigational status distribution dashboard.
    columns:
      - name: month_start_date
        description: First day of the month (used for partitioning)
        tests:
          - not_null
      
      - name: year
        description: Year extracted from the event date
        tests:
          - not_null
      
      - name: month
        description: Month number (1-12) extracted from the event date
        tests:
          - not_null
      
      - name: year_month
        description: Year and month formatted as YYYY-MM for easy display
        tests:
          - not_null
      
      - name: navigational_status
        description: The navigational status reported by the vessel
        tests:
          - not_null
      
      - name: vessel_count
        description: Count of distinct vessels (by MMSI) for each navigational status per month
        tests:
          - not_null
      
      - name: avg_daily_vessels
        description: Average number of distinct vessels per day within the month
        tests:
          - not_null
      
      - name: record_count
        description: Total count of AIS records for each navigational status per month
        tests:
          - not_null
      
      - name: days_count
        description: Number of distinct days with data in this month
        tests:
          - not_null
      
      - name: movement_status
        description: Categorized movement status (Anchored, Moored, Moving, Other)
      
      - name: generated_at
        description: Timestamp when this data was generated
